import { EstatePropertyModel } from "../models/estate-property.type";

export const PROPERTY_LIST: EstatePropertyModel[] = [
  {
    id: "prop-0",
    name: "GrandHouse",
    address: "Virginia Boulevard 1444/32, San Francisco",
    type: "house",
    dayRental: 20,
    weekRental: 600,
    monthRental: 4500,
    roomCount: 5,
    bathroomCount: 2,
    garageSlots: 1,
    pool: true,
    airConditioner: true,
    freeWifi: true,
    livingSurface: 185,
    mainImage:
      "https://ap.rdcpix.com/c24e81a0a097277bde52fc1f824e02b8l-b1117342834od-w480_h360.jpg",
    images: [""],
  },
  {
    id: "prop-1",
    name: "SandStudio",
    address: "John F. Kennedy 665/32, San Francisco",
    type: "house",
    dayRental: 23,
    weekRental: 650,
    monthRental: 4700,
    roomCount: 3,
    bathroomCount: 1,
    garageSlots: 1,
    pool: false,
    airConditioner: true,
    freeWifi: true,
    livingSurface: 160,
    mainImage:
      "https://ap.rdcpix.com/882ed7b005e6417df48846ea26273e55l-m713790322od-w480_h360.jpg",
    images: [""],
  },
  {
    id: "prop-2",
    name: "MatonniHill",
    address: "Cumberland St 102/4, San Francisco",
    type: "apartment",
    dayRental: 23,
    weekRental: 650,
    monthRental: 4700,
    roomCount: 3,
    bathroomCount: 1,
    garageSlots: 1,
    pool: true,
    airConditioner: true,
    freeWifi: true,
    livingSurface: 160,
    mainImage:
      "https://ap.rdcpix.com/09c3c985cdb2bb2639945ab2688082abl-m3075208526od-w480_h360.jpg",
    images: [""],
  },
  {
    id: "prop-3",
    name: "BlackWall",
    address: "Caselli Ave 609/12, San Francisco",
    type: "apartment",
    dayRental: 40,
    weekRental: 790,
    monthRental: 5200,
    roomCount: 4,
    bathroomCount: 1,
    garageSlots: 1,
    pool: true,
    airConditioner: true,
    freeWifi: true,
    livingSurface: 160,
    mainImage:
      "https://images.homes.com/listings/215/1132796063-737148861-original.jpg",
    images: [""],
  },
  {
    id: "prop-4",
    name: "BakersField",
    address: "Deming St 209/5, San Francisco",
    type: "house",
    dayRental: 46,
    weekRental: 750,
    monthRental: 5100,
    roomCount: 3,
    bathroomCount: 1,
    garageSlots: 1,
    pool: false,
    airConditioner: true,
    freeWifi: true,
    livingSurface: 170,
    mainImage:
      "https://u.realgeeks.media/bakersfieldcah/bakersfield-real-estate/nw-homes-for-sale.jpg",
    images: [""],
  },
  {
    id: "prop-5",
    name: "VirginiaBlock",
    address: "Vanilla Ice 404/11, San Francisco",
    type: "apartment",
    dayRental: 40,
    weekRental: 670,
    monthRental: 4700,
    roomCount: 2,
    bathroomCount: 1,
    garageSlots: 1,
    pool: false,
    airConditioner: true,
    freeWifi: true,
    livingSurface: 170,
    mainImage:
      "https://www.sfassessor.org/sites/default/files/tool/houses-06.jpg",
    images: [""],
  },
];
